# -*- mode: ruby -*-
# vi: set ft=ruby :

file_to_disk = 'large_disk.vdi'


Vagrant.configure("2") do |config|
  config.vm.define :web do |web_config|
    web_config.vm.box = "fedora/30-cloud-base"
    #web_config.vm.forward_port 80, 8080
    web_config.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define :db do |db_config|
    db_config.vm.box = "fedora/30-cloud-base"
    #db_config.vm.forward_port 3306, 3306
    db_config.vm.network "private_network", ip: "192.168.33.11"
  end
end


  



#  config.vm.customize [ "createmedium", "disk", "--filename", "mydisk.vmdk", "--format", "vmdk", "--size", 1024 * 10 ]
#  config.vm.customize [ "storageattach", "myvm" , "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "mydisk.vmdk"]
  
